version: 1

ls:
  .dir: snake_case
  .*: snake_case
  .md: snake_case | regex:[0-9A-Z\-]+
  .txt: snake_case | kebab-case
  .yml: snake_case | kebab-case

rules:
  filename:
    regex: '^[a-z0-9_]+$'
    match: true

ignore:
  - .git
  - .github
  - .vscode
  - "**/.vscode/**"
  - venv
  - .ruff_cache
  - .pytest_cache
  - __pycache__
  - .ls-lint.yml
  - .markdownlint.yml
  - "**/node_modules"
  - README.md
